### ISSUE TITLE
Failed Environment solve

### ISSUE THREAD

**Issue by jessepisel** [learn-co-curriculum/dsc-m1tf#1]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

### Source

```

```

### Concern

Followed the steps to remove anaconda, install miniconda, and when I create the environment it rails to solve the environment and has a whole slew of packages that it could not find:
`ollecting package metadata (repodata.json): done                                       
Solving environment: failed                                                             
                                                                                        
ResolvePackageNotFound:                                                                 
  - py-xgboost=1.2.0                                                                    
  - libopenblas=0.3.10                                                                  
  - liblapacke=3.8.0                                                                    
  - libxgboost=1.2.0                                                                    
  - libclang-cpp10=10.0.1                                                               
  - matplotlib=3.3.1                                                                    
  - fbprophet=0.7.1                                                                     
  - clang_osx-64=10.0.1                                                                 
  - netcdf4=1.5.4                                                                       
  - aiohttp=3.6.2                                                                       
  - osqp=0.6.1                                                                          
  - libgfortran=4.0.0                                                                   
  - cftime=1.2.1                                                                        
  - intel-openmp=2020.2                                                                 
  - libcblas=3.8.0                                                                      
  - statsmodels=0.12.0                                                                  
  - google-crc32c=1.0.0                                                                 
  - ipython=7.18.1                                                                      
  - lxml=4.5.2                                                                          
  - numpy-base=1.19.1                                                                   
  - pillow=7.2.0                                                                        
  - scikit-surprise=1.1.1                                                               
  - gensim=3.8.3                                                                        
  - libcxx=10.0.1                                                                       
  - pyzmq=19.0.2      
  - libblas=3.8.0
  - clang=10.0.1
  - mkl_fft=1.2.0
  - krb5=1.18.2
  - libgfortran4=7.5.0
  - liblapack=3.8.0
  - pandoc=2.10.1
  - libnetcdf=4.7.4
  - tornado=6.0.4
  - blas=2.17
  - compiler-rt=10.0.1
  - yarl=1.6.2
  - ephem=3.7.7.1
  - grpcio=1.31.0
  - mkl-service=2.3.0
  - mkl=2020.2
  - cvxpy-base=1.1.6
  - clangxx_osx-64=10.0.1
  - matplotlib-base=3.3.1
  - setuptools=50.3.0
  - jupyter_latex_envs=1.4.4
  - kiwisolver=1.2.0
  - regex=2020.10.11
  - notebook=6.1.4
  - cvxpy=1.1.6
  - clangxx=10.0.1
  - freetype=2.10.3
  - mkl_random=1.2.0
  - tapi=1000.10.8
`

## What OS Are You Using?

- [x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

## Any Additional Context?

I have tried with Python 3.10, 3.9 and 3.8 with no luck so far

**Comment by jessepisel** [comment]
@bpurdy-ds I think we discussed where I went wrong with this and you updated the README instructions is that correct?

**Comment by bpurdy-ds** [comment]
@jessepisel Did you run into this same issue when you tried?

**Comment by jessepisel** [comment]
This worked as intended last week. I am closing this issue at this time
